runs:
  using: "composite"
    steps:
      - name: Message about starting
        run: echo Pip and deps installing has started
        shell: bash
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/python-greetings'
          path: 'py-gre'
      - name: Install dependecies
        working-directory: py-gre
        run: pip install -r requirements.txt
        shell: bash